version: "3.8"
services:
  web-tdd:
    build: ./project
    command: pdm run uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    depends_on:
      - web-tdd-db
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    ports:
      - 8004:8000
    volumes:
      - ./project:/usr/src/app
  web-tdd-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
