version: "3.8"
services:
  web-tdd:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: pdm run uvicorn app.main:app --reload --port=8000 --host=0.0.0.0
    depends_on:
      - web-tdd-db
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-tdd-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-tdd-db:5432/web_test
    ports:
      - 8004:8000
    volumes:
      - ./app:/project/app
  web-tdd-db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
